name = "my-first-worker"
main = "src/index.ts"
compatibility_date = "2022-05-12"

[build]
command = "npm run build"

[durable_objects]
bindings = [{name = "COUNTER", class_name = "Counter"}]

[[migrations]]
tag = "v1" # Should be unique for each entry TODO: migrationの方法を調べる
new_classes = ["Counter"]
